// <auto-generated />
namespace TeacherHelper.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class subjects2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(subjects2));
        
        string IMigrationMetadata.Id
        {
            get { return "201904191530551_subjects2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
